# QCArchive Demo
MolSSI Software Summer School -Day 2

In [2]:
import qcportal as ptl
client = ptl.FractalClient()

In [3]:
client

FractalClient(server_name='The MolSSI QCArchive Server', address='https://api.qcarchive.molssi.org:443/', username='None')

In [33]:
# pull down butane molecule
butane = client.query_molecules(id=['61139', '70695']) # two diff molecules

In [34]:
butane

[<Molecule(name='C4H10' formula='C4H10' hash='3bbc6db')>,
 <Molecule(name='C4H10' formula='C4H10' hash='eb4ef55')>]

In [35]:
butane[0].show()

You appear to be running in JupyterLab (or JavaScript failed to load for some other reason). You need to install the 3dmol extension: 
 jupyter labextension install jupyterlab_3dmol

In [36]:
butane[1].show()

You appear to be running in JupyterLab (or JavaScript failed to load for some other reason). You need to install the 3dmol extension: 
 jupyter labextension install jupyterlab_3dmol

In [37]:
dir(butane)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [38]:
butane[0].atomic_numbers

[6, 6, 6, 6, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [39]:
butane[0].geometry

array([[ 0.60309252, -2.0666753 , -2.95631542],
       [-0.54975128,  2.07257294,  2.96267825],
       [ 0.17543623, -1.41965569, -0.1899598 ],
       [-0.17535536,  1.41986451,  0.18990506],
       [-0.98243014, -1.42706018, -4.12126516],
       [ 2.32107194, -1.14665691, -3.64966894],
       [ 0.81868895, -4.10783439, -3.21556669],
       [ 1.07104045,  1.43010767,  4.07529687],
       [-2.24715359,  1.16149057,  3.71618302],
       [-0.73832413,  4.11600143,  3.22440978],
       [ 1.79270627, -2.08396319,  0.92115557],
       [-1.4961426 , -2.4339562 ,  0.49460988],
       [-1.81551707,  2.07754179, -0.89074739],
       [ 1.48034939,  2.43606453, -0.52991943]])

In [40]:
dir(butane[0])

['Config',
 '__abstractmethods__',
 '__annotations__',
 '__class__',
 '__config__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__fields__',
 '__fields_set__',
 '__format__',
 '__ge__',
 '__get_validators__',
 '__getattr__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '__validators__',
 '__values__',
 '__weakref__',
 '_abc_impl',
 '_calculate_keys',
 '_custom_root_type',
 '_decompose_class',
 '_get_key_factory',
 '_get_value',
 '_inertial_tensor',
 '_iter',
 '_json_encoder',
 '_orient_molecule_internal',
 '_repr_html_',
 '_schema_cache',
 'align',
 'atom_labels',
 'atomic_numbers',
 'comment',
 'compare',
 'connectivity',
 'construct',
 'copy',
 'dict',
 'extras',
 'fields',
 'fix_com',
 'fix_orientat

In [49]:
butane[0].symbols

['C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H']

In [50]:
butane[0].geometry

array([[ 0.60309252, -2.0666753 , -2.95631542],
       [-0.54975128,  2.07257294,  2.96267825],
       [ 0.17543623, -1.41965569, -0.1899598 ],
       [-0.17535536,  1.41986451,  0.18990506],
       [-0.98243014, -1.42706018, -4.12126516],
       [ 2.32107194, -1.14665691, -3.64966894],
       [ 0.81868895, -4.10783439, -3.21556669],
       [ 1.07104045,  1.43010767,  4.07529687],
       [-2.24715359,  1.16149057,  3.71618302],
       [-0.73832413,  4.11600143,  3.22440978],
       [ 1.79270627, -2.08396319,  0.92115557],
       [-1.4961426 , -2.4339562 ,  0.49460988],
       [-1.81551707,  2.07754179, -0.89074739],
       [ 1.48034939,  2.43606453, -0.52991943]])

In [52]:
print(len(butane[0].geometry))
print(len(butane[0].symbols))

# we are dealing with qcarchive molecules

14
14


In [41]:
butane_geometries =[butane[0].geometry.copy(), butane[1].geometry.copy()]

In [54]:
butane_geometries # first 4 lines are the coordinates for four  C atoms and so on

[array([[ 0.60309252, -2.0666753 , -2.95631542],
        [-0.54975128,  2.07257294,  2.96267825],
        [ 0.17543623, -1.41965569, -0.1899598 ],
        [-0.17535536,  1.41986451,  0.18990506],
        [-0.98243014, -1.42706018, -4.12126516],
        [ 2.32107194, -1.14665691, -3.64966894],
        [ 0.81868895, -4.10783439, -3.21556669],
        [ 1.07104045,  1.43010767,  4.07529687],
        [-2.24715359,  1.16149057,  3.71618302],
        [-0.73832413,  4.11600143,  3.22440978],
        [ 1.79270627, -2.08396319,  0.92115557],
        [-1.4961426 , -2.4339562 ,  0.49460988],
        [-1.81551707,  2.07754179, -0.89074739],
        [ 1.48034939,  2.43606453, -0.52991943]]),
 array([[ 1.55958149, -2.11778768, -1.41169778],
        [ 0.73067991,  2.34522977,  1.69620783],
        [-1.19404014, -1.32947022, -1.00331889],
        [-1.63560999,  1.04919218,  0.6514071 ],
        [ 2.62796281, -0.60101876, -2.39028195],
        [ 2.4766323 , -2.58350622,  0.41635249],
        [ 1.616278

In [55]:
# takes two numpy array with 1 row 3 columns each
import numpy as np
r1 = np.array([0.0, 0.0, 0.0])
r2 = np.array([0.0, 0.1, 0.0])

def calculate_distance(rA, rB):
    '''Calculate the distance between A and B'''
    dist_vec = (rA-rB)
    distance = np.linalg.norm(dist_vec)
    return distance

In [56]:
atom1 = butane_geometries[0][0] # cooordinates of the first atom
print(atom1)

[ 0.60309252 -2.0666753  -2.95631542]


In [57]:
atom2 = butane_geometries[0][1] # cooordinates of the second atom
print(atom2)

[-0.54975128  2.07257294  2.96267825]


In [58]:
measured_distance  = calculate_distance(atom1, atom2)
print(measured_distance)

7.314158248564329


In [59]:
butane[0].measure([0,1]) # qcarchive has inbuilt fun

7.31415824856433

In [70]:
# Use caclculate_disance function to measure the distance in between 3 and 10 
#in the second butane molecule
atom3 = butane_geometries[1][2]
atom10 = butane_geometries[1][9]
print(atom3)
print(atom10)


[-1.19404014 -1.32947022 -1.00331889]
[0.15987798 4.00916586 2.84053853]


In [73]:
measured_distance = calculate_distance(atom3, atom10)
print(measured_distance)

6.716350894319858


In [74]:
butane[1].measure([2,9])

6.716350894319858

In [43]:
def build_bond_list(coordinates, max_bond = 1.55, min_bond=0): # max and min bond distance, optional arguments
    num_atoms = len(coordinates)
    bonds = {}
    for atom1 in range(num_atoms):
        for atom2 in range(atom1, num_atoms):
            distance = calculate_distance(coordinates[atom1], coordinates[atom2])
            
            if distance > min_bond and distance < max_bond:
                bonds[(atom1, atom2)] = distance
    
    return bonds

In [75]:
bond_list = build_bond_list(butane_geometries[0], max_bond = 2.93) # changed into bohr from angstrom

In [77]:
bond_list

{(0, 2): 2.873020656801253,
 (0, 4): 2.068839651551603,
 (0, 5): 2.068484041315794,
 (0, 6): 2.068821759435787,
 (1, 3): 2.873059651780396,
 (1, 7): 2.068247482474781,
 (1, 8): 2.0685780442929644,
 (1, 9): 2.0687346633381822,
 (2, 3): 2.8862132661474598,
 (2, 10): 2.0715801221019885,
 (2, 11): 2.0716218178677623,
 (3, 12): 2.0713472807014583,
 (3, 13): 2.071754810836534}

In [78]:
butane[0].connectivity # we can get from qcarchive and compare, first two are atoms

[(0, 2, 1.0),
 (0, 4, 1.0),
 (0, 5, 1.0),
 (0, 6, 1.0),
 (1, 3, 1.0),
 (1, 7, 1.0),
 (1, 8, 1.0),
 (1, 9, 1.0),
 (2, 3, 1.0),
 (2, 10, 1.0),
 (2, 11, 1.0),
 (3, 12, 1.0),
 (3, 13, 1.0)]

In [48]:
import qcelemental
angstrom_to_bohr = qcelemental.constants.conversion_factor("angstrom", "bohr")


In [79]:
# Use to access a geometry optimization calculation
# use query_procedures
# id = 2658710

In [87]:
calculation = client.query_procedures(id=['2658710'])

In [88]:
calculation

[<OptimizationRecord(id='2658710' status='COMPLETE')>]

In [89]:
dir(calculation)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [90]:
opt = calculation[0]

IndexError: list index out of range

In [97]:
initial = opt.get_initial_molecule()
initial.show()

You appear to be running in JupyterLab (or JavaScript failed to load for some other reason). You need to install the 3dmol extension: 
 jupyter labextension install jupyterlab_3dmol

In [98]:
final = opt.get_final_molecule()
final.show()

You appear to be running in JupyterLab (or JavaScript failed to load for some other reason). You need to install the 3dmol extension: 
 jupyter labextension install jupyterlab_3dmol

In [ ]:
# max_bond length is 2.93



In [100]:
initial.connectivity

In [102]:
# max bond length is 2.93
initial_coordinates = initial.geometry.copy()
final_coordinates = final.geometry.copy()

initial_bonds = build_bond_list(initial_coordinates, max_bond=2.93)
final_bonds = build_bond_list(final_coordinates, max_bond=2.93)

In [103]:
initial_bonds

{(0, 1): 2.6853008199999997,
 (0, 5): 2.685300947458371,
 (0, 54): 2.0494834766860643,
 (1, 6): 2.6853009524690883,
 (1, 55): 2.0494834766860643,
 (2, 3): 2.6853008199999997,
 (2, 9): 2.685300947458371,
 (2, 56): 2.0494834766860643,
 (3, 10): 2.6853009524690883,
 (3, 57): 2.0494834766860643,
 (4, 5): 2.685300829999999,
 (4, 13): 2.685300829993184,
 (4, 58): 2.0494834770587396,
 (5, 14): 2.6852998829666923,
 (6, 7): 2.68530082,
 (6, 15): 2.6852998879774117,
 (7, 16): 2.6852998879774117,
 (7, 59): 2.0494834871062877,
 (8, 9): 2.685300829999999,
 (8, 19): 2.685300829993184,
 (8, 60): 2.0494834770587396,
 (9, 20): 2.6852998829666923,
 (10, 11): 2.68530082,
 (10, 21): 2.6852998879774117,
 (11, 22): 2.6852998879774117,
 (11, 61): 2.0494834871062877,
 (12, 13): 2.685300829999999,
 (12, 24): 2.6852998829666923,
 (12, 62): 2.049483475383679,
 (13, 25): 2.685300829993184,
 (14, 15): 2.6853008199999997,
 (14, 26): 2.6852998829666923,
 (15, 27): 2.6852998879774117,
 (16, 17): 2.68530082,
 (16, 28)

In [101]:
# Compare the two dictionaries initial_bonds and final_bonds to find the change in bond length